/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrabalhosPinheiroVargasRouteImport } from './routes/trabalhos/pinheiro-vargas'
import { Route as TrabalhosMestreCilsoRouteImport } from './routes/trabalhos/mestre-cilso'
import { Route as TrabalhosInstitutoDellerRouteImport } from './routes/trabalhos/instituto-deller'
import { Route as TrabalhosAaamupRouteImport } from './routes/trabalhos/aaamup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhosPinheiroVargasRoute = TrabalhosPinheiroVargasRouteImport.update({
  id: '/trabalhos/pinheiro-vargas',
  path: '/trabalhos/pinheiro-vargas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhosMestreCilsoRoute = TrabalhosMestreCilsoRouteImport.update({
  id: '/trabalhos/mestre-cilso',
  path: '/trabalhos/mestre-cilso',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhosInstitutoDellerRoute =
  TrabalhosInstitutoDellerRouteImport.update({
    id: '/trabalhos/instituto-deller',
    path: '/trabalhos/instituto-deller',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrabalhosAaamupRoute = TrabalhosAaamupRouteImport.update({
  id: '/trabalhos/aaamup',
  path: '/trabalhos/aaamup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trabalhos/aaamup': typeof TrabalhosAaamupRoute
  '/trabalhos/instituto-deller': typeof TrabalhosInstitutoDellerRoute
  '/trabalhos/mestre-cilso': typeof TrabalhosMestreCilsoRoute
  '/trabalhos/pinheiro-vargas': typeof TrabalhosPinheiroVargasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trabalhos/aaamup': typeof TrabalhosAaamupRoute
  '/trabalhos/instituto-deller': typeof TrabalhosInstitutoDellerRoute
  '/trabalhos/mestre-cilso': typeof TrabalhosMestreCilsoRoute
  '/trabalhos/pinheiro-vargas': typeof TrabalhosPinheiroVargasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trabalhos/aaamup': typeof TrabalhosAaamupRoute
  '/trabalhos/instituto-deller': typeof TrabalhosInstitutoDellerRoute
  '/trabalhos/mestre-cilso': typeof TrabalhosMestreCilsoRoute
  '/trabalhos/pinheiro-vargas': typeof TrabalhosPinheiroVargasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/trabalhos/aaamup'
    | '/trabalhos/instituto-deller'
    | '/trabalhos/mestre-cilso'
    | '/trabalhos/pinheiro-vargas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/trabalhos/aaamup'
    | '/trabalhos/instituto-deller'
    | '/trabalhos/mestre-cilso'
    | '/trabalhos/pinheiro-vargas'
  id:
    | '__root__'
    | '/'
    | '/trabalhos/aaamup'
    | '/trabalhos/instituto-deller'
    | '/trabalhos/mestre-cilso'
    | '/trabalhos/pinheiro-vargas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrabalhosAaamupRoute: typeof TrabalhosAaamupRoute
  TrabalhosInstitutoDellerRoute: typeof TrabalhosInstitutoDellerRoute
  TrabalhosMestreCilsoRoute: typeof TrabalhosMestreCilsoRoute
  TrabalhosPinheiroVargasRoute: typeof TrabalhosPinheiroVargasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos/pinheiro-vargas': {
      id: '/trabalhos/pinheiro-vargas'
      path: '/trabalhos/pinheiro-vargas'
      fullPath: '/trabalhos/pinheiro-vargas'
      preLoaderRoute: typeof TrabalhosPinheiroVargasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos/mestre-cilso': {
      id: '/trabalhos/mestre-cilso'
      path: '/trabalhos/mestre-cilso'
      fullPath: '/trabalhos/mestre-cilso'
      preLoaderRoute: typeof TrabalhosMestreCilsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos/instituto-deller': {
      id: '/trabalhos/instituto-deller'
      path: '/trabalhos/instituto-deller'
      fullPath: '/trabalhos/instituto-deller'
      preLoaderRoute: typeof TrabalhosInstitutoDellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhos/aaamup': {
      id: '/trabalhos/aaamup'
      path: '/trabalhos/aaamup'
      fullPath: '/trabalhos/aaamup'
      preLoaderRoute: typeof TrabalhosAaamupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrabalhosAaamupRoute: TrabalhosAaamupRoute,
  TrabalhosInstitutoDellerRoute: TrabalhosInstitutoDellerRoute,
  TrabalhosMestreCilsoRoute: TrabalhosMestreCilsoRoute,
  TrabalhosPinheiroVargasRoute: TrabalhosPinheiroVargasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
